name = "FractalTools"
uuid = "b405c40b-1ee4-4202-972e-f2b10e481766"
authors = ["Zekeriya Sarı", "Gizem Kalender"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
